from array import *
def Cell (self):
    A1 = ['1', '1', 'WHITE', 'ROOK']
    A2 = ['1', '2', 'WHITE', 'PAWN']
    A3 = ['1', '3', '', 'NONE']
    A4 = ['1', '4', '', 'NONE']
    A5 = ['1', '5', '', 'NONE']
    A6 = ['1', '6', '', 'NONE']
    A7 = ['1', '7', 'BLACK', 'PAWN']
    A8 = ['1', '8', 'BLACK', 'ROOK']

    
    B1 = ['2', '1', 'WHITE', 'KNIGHT']
    B2 = ['2', '2', 'WHITE', 'PAWN']
    B3 = ['2', '3', '', 'NONE']
    B4 = ['2', '4', '', 'NONE']
    B5 = ['2', '5', '', 'NONE']
    B6 = ['2', '6', '', 'NONE']
    B7 = ['2', '7', 'BLACK', 'PAWN']
    B8 = ['2', '8', 'BLACK', 'KNIGHT']

    C1 = ['3', '1', 'WHITE', 'BISHOP']
    C2 = ['3', '2', 'WHITE', 'PAWN']
    C3 = ['3', '3', '', 'NONE']
    C4 = ['3', '4', '', 'NONE']
    C5 = ['3', '5', '', 'NONE']
    C6 = ['3', '6', '', 'NONE']
    C7 = ['3', '7', 'BLACK', 'PAWN']
    C8 = ['3', '8', 'BLACK', 'BISHOP']

    D1 = ['4', '1', 'WHITE', 'QUEEN']
    D2 = ['4', '2', 'WHITE', 'PAWN']
    D3 = ['4', '3', '', 'NONE']
    D4 = ['4', '4', '', 'NONE']
    D5 = ['4', '5', '', 'NONE']
    D6 = ['4', '6', '', 'NONE']
    D7 = ['4', '7', 'BLACK', 'PAWN']
    D8 = ['4', '8', 'BLACK', 'QUEEN']

    E1 = ['5', '1', 'WHITE', 'KING']
    E2 = ['5', '2', 'WHITE', 'PAWN']
    E3 = ['5', '3', '', 'NONE']
    E4 = ['5', '4', '', 'NONE']
    E5 = ['5', '5', '', 'NONE']
    E6 = ['5', '6', '', 'NONE']
    E7 = ['5', '7', 'BLACK', 'PAWN']
    E8 = ['5', '8', 'BLACK', 'KING']

    F1 = ['6', '1', 'WHITE', 'BISHOP']
    F2 = ['6', '2', 'WHITE', 'PAWN']
    F3 = ['6', '3', '', 'NONE']
    F4 = ['6', '4', '', 'NONE']
    F5 = ['6', '5', '', 'NONE']
    F6 = ['6', '6', '', 'NONE']
    F7 = ['6', '7', 'BLACK', 'PAWN']
    F8 = ['6', '8', 'BLACK', 'BISHOP']

    G1 = ['7', '1', 'WHITE', 'KNIGHT']
    G2 = ['7', '2', 'WHITE', 'PAWN']
    G3 = ['7', '3', '', 'NONE']
    G4 = ['7', '4', '', 'NONE']
    G5 = ['7', '5', '', 'NONE']
    G6 = ['7', '6', '', 'NONE']
    G7 = ['7', '7', 'BLACK', 'PAWN']
    G8 = ['7', '8', 'BLACK', 'KNIGHT']

    H1 = ['8', '1', 'WHITE', 'ROOK']
    H2 = ['8', '2', 'WHITE', 'PAWN']
    H3 = ['8', '3', '', 'NONE']
    H4 = ['8', '4', '', 'NONE']
    H5 = ['8', '5', '', 'NONE']
    H6 = ['8', '6', '', 'NONE']
    H7 = ['8', '7', 'BLACK', 'PAWN']
    H8 = ['8', '8', 'BLACK', 'ROOK']
    
    
